### PR TITLE
Properly initialize the logger.

### PR DESCRIPTION
**Pull request by metlos**
### What does this PR do?
Initializes the logging subsystem so that logs are printed to the std output.

### CODE REVIEW

**Comment by metlos** [comment]
> zap logger? why that one ?

because it was already transitively included (e.g. no additions to go.sum).

**Comment by metlos** [comment]
Superseded by #10.

**Comment by sparkoo** [comment]
> > zap logger? why that one ?
> 
> because it was already transitively included (e.g. no additions to go.sum).

I see https://github.com/kubernetes-sigs/controller-runtime/blob/master/go.mod#L19

**Comment by sparkoo** [comment]
> Superseded by #10.

can we close this one then ?

**Pull request closed without merging**
